// Emits the Soroban-side artifacts for the payment-policy circuit:
//   contracts/zentra-verifier/src/vk.rs              (verification key builder)
//   contracts/zentra-verifier/src/payment_fixtures.rs (sample proof + 14 public signals, test-only)
//
// All byte serialization comes from @zentra/serialization — the single
// canonical codec (G1 = be(X)||be(Y), G2 = c1-before-c0, Fr = 32B BE),
// matching soroban-sdk v26 bn254.
//
// Usage: pnpm exec tsx to-soroban-vk.ts [--out-dir <dir>]
//   --out-dir overrides the destination (default contracts/zentra-verifier/src),
//   e.g. to diff a regenerated vk.rs against the committed one.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  be32,
  g1ToBytes,
  g2ToBytes,
  vkToBytes,
  type Groth16Proof,
  type Groth16VerificationKey,
} from "../../packages/serialization/src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const outDirIdx = argv.indexOf("--out-dir");
const outDir =
  outDirIdx !== -1 && argv[outDirIdx + 1]
    ? resolve(argv[outDirIdx + 1])
    : resolve(here, "../../contracts/zentra-verifier/src");

const read = (f: string) => JSON.parse(readFileSync(resolve(here, f), "utf8"));
const vk: Groth16VerificationKey = read("verification_key.json");
const proof: Groth16Proof = read("proof.json");
const pub: string[] = read("public.json");

const arr = (name: string, b: Uint8Array) =>
  `pub const ${name}: [u8; ${b.length}] = [${Array.from(b).join(", ")}];`;
const arr2 = (name: string, rows: Uint8Array[]) =>
  `pub const ${name}: [[u8; ${rows[0].length}]; ${rows.length}] = [\n${rows.map((b) => `    [${Array.from(b).join(", ")}]`).join(",\n")},\n];`;

const vkb = vkToBytes(vk);
const vkRs = `// @generated by circuits/payment-policy/to-soroban-vk.ts — DO NOT EDIT BY HAND.
// Groth16/BN254 verification key for payment_policy.circom (${vkb.ic.length} IC points, ${vkb.ic.length - 1} public inputs).
use soroban_sdk::{
    crypto::bn254::{Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
    Env, Vec,
};

use crate::groth16::VerificationKey;

${arr("ALPHA", vkb.alpha)}
${arr("BETA", vkb.beta)}
${arr("GAMMA", vkb.gamma)}
${arr("DELTA", vkb.delta)}
${arr2("IC", vkb.ic)}

/// Build the payment-policy verification key in soroban-sdk byte form.
pub fn verification_key(env: &Env) -> VerificationKey {
    let mut ic = Vec::new(env);
    for p in IC.iter() {
        ic.push_back(G1Affine::from_array(env, p));
    }
    VerificationKey {
        alpha: G1Affine::from_array(env, &ALPHA),
        beta: G2Affine::from_array(env, &BETA),
        gamma: G2Affine::from_array(env, &GAMMA),
        delta: G2Affine::from_array(env, &DELTA),
        ic,
    }
}
`;
writeFileSync(resolve(outDir, "vk.rs"), vkRs);

const pubRows = pub.map(be32);
const fxRs = `// @generated by circuits/payment-policy/to-soroban-vk.ts — DO NOT EDIT BY HAND.
// Sample payment-policy proof + its ${pubRows.length} public signals (test-only fixture).
#![allow(dead_code)]

${arr("PROOF_A", g1ToBytes(proof.pi_a))}
${arr("PROOF_B", g2ToBytes(proof.pi_b))}
${arr("PROOF_C", g1ToBytes(proof.pi_c))}

${arr2("PUB_SIGNALS", pubRows)}
`;
writeFileSync(resolve(outDir, "payment_fixtures.rs"), fxRs);

console.log(
  `wrote ${resolve(outDir, "vk.rs")} (${vkb.ic.length} IC points) and payment_fixtures.rs (${pubRows.length} public signals)`,
);
