// Converts snarkjs Groth16/BN254 artifacts (verification_key.json, proof.json,
// public.json) into a Rust fixtures module (Phase-0 spike only — the verifier
// crate no longer embeds this; its payment fixtures come from
// circuits/payment-policy/to-soroban-vk.ts).
//
// All byte serialization comes from @zentra/serialization — the single
// canonical codec (G1 = be(X)||be(Y), G2 = c1-before-c0 / EIP-197 imaginary
// first, Fr = 32B BE), matching soroban-sdk v26 bn254.
//
// Usage: pnpm exec tsx to-soroban.ts [--out-dir <dir>]   (run from circuits/spike/)
//   Writes spike_fixtures.rs into circuits/spike/ (gitignored scratch output)
//   unless --out-dir says otherwise.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  be32,
  g1ToBytes,
  g2ToBytes,
  vkToBytes,
  type Groth16Proof,
  type Groth16VerificationKey,
} from "../../packages/serialization/src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const outDirIdx = argv.indexOf("--out-dir");
const outDir = outDirIdx !== -1 && argv[outDirIdx + 1] ? resolve(argv[outDirIdx + 1]) : here;

const read = (f: string) => JSON.parse(readFileSync(resolve(here, f), "utf8"));

const vk: Groth16VerificationKey = read("verification_key.json");
const proof: Groth16Proof = read("proof.json");
const pub: string[] = read("public.json");

function rustArr(name: string, bytes: Uint8Array): string {
  const body = Array.from(bytes).join(", ");
  return `pub const ${name}: [u8; ${bytes.length}] = [${body}];`;
}
function rustArr2(name: string, rows: Uint8Array[]): string {
  const inner = rows.map((b) => `    [${Array.from(b).join(", ")}]`).join(",\n");
  return `pub const ${name}: [[u8; ${rows[0].length}]; ${rows.length}] = [\n${inner},\n];`;
}

const vkb = vkToBytes(vk);
const pubRows = pub.map(be32);

const out = `// @generated by circuits/spike/to-soroban.ts — DO NOT EDIT BY HAND.
// BN254 Groth16 fixtures for the Phase-0 verifier spike (a*b=c, c public = ${pub.join(",")}).
#![allow(dead_code)]

${rustArr("ALPHA", vkb.alpha)}
${rustArr("BETA", vkb.beta)}
${rustArr("GAMMA", vkb.gamma)}
${rustArr("DELTA", vkb.delta)}
${rustArr2("IC", vkb.ic)}

${rustArr("PI_A", g1ToBytes(proof.pi_a))}
${rustArr("PI_B", g2ToBytes(proof.pi_b))}
${rustArr("PI_C", g1ToBytes(proof.pi_c))}

${rustArr2("PUB_SIGNALS", pubRows)}
`;

const dest = resolve(outDir, "spike_fixtures.rs");
writeFileSync(dest, out);
console.log(`wrote ${dest}`);
console.log(`  IC points: ${vkb.ic.length}, public signals: ${pubRows.length} (${pub.join(",")})`);
