// @generated-by: none — this is the generator.
// Converts snarkjs Groth16/BN254 artifacts (verification_key.json, proof.json,
// public.json) into a Rust fixtures module the Soroban verifier test can embed.
//
// Byte layout (matches soroban-sdk v26 bn254 module, verified against docs):
//   G1 (64 bytes):  be(X) || be(Y)
//   G2 (128 bytes): be(X.c1) || be(X.c0) || be(Y.c1) || be(Y.c0)   (imaginary first, EIP-197)
//   Fr (32 bytes):  big-endian
//
// snarkjs stores G2 as [[x_c0, x_c1], [y_c0, y_c1], [1,0]], so we swap each pair.
//
// Usage: node to-soroban.mjs   (run from circuits/spike/)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => JSON.parse(readFileSync(resolve(here, f), "utf8"));

const vk = read("verification_key.json");
const proof = read("proof.json");
const pub = read("public.json");

/** decimal string -> 32-byte big-endian Uint8Array */
function be32(dec) {
  let n = BigInt(dec);
  if (n < 0n) throw new Error(`negative value: ${dec}`);
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  if (n !== 0n) throw new Error(`value exceeds 32 bytes: ${dec}`);
  return out;
}
const cat = (...arrs) => {
  const total = arrs.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const a of arrs) {
    out.set(a, o);
    o += a.length;
  }
  return out;
};

const g1 = (p) => cat(be32(p[0]), be32(p[1])); // 64 bytes
const g2 = (p) => cat(be32(p[0][1]), be32(p[0][0]), be32(p[1][1]), be32(p[1][0])); // 128 bytes

function rustArr(name, bytes) {
  const body = Array.from(bytes).join(", ");
  return `pub const ${name}: [u8; ${bytes.length}] = [${body}];`;
}
function rustArr2(name, rows) {
  const inner = rows
    .map((b) => `    [${Array.from(b).join(", ")}]`)
    .join(",\n");
  return `pub const ${name}: [[u8; ${rows[0].length}]; ${rows.length}] = [\n${inner},\n];`;
}

const icRows = vk.IC.map(g1);
const pubRows = pub.map(be32);

const out = `// @generated by circuits/spike/to-soroban.mjs — DO NOT EDIT BY HAND.
// BN254 Groth16 fixtures for the Phase-0 verifier spike (a*b=c, c public = ${pub.join(",")}).
#![allow(dead_code)]

${rustArr("ALPHA", g1(vk.vk_alpha_1))}
${rustArr("BETA", g2(vk.vk_beta_2))}
${rustArr("GAMMA", g2(vk.vk_gamma_2))}
${rustArr("DELTA", g2(vk.vk_delta_2))}
${rustArr2("IC", icRows)}

${rustArr("PI_A", g1(proof.pi_a))}
${rustArr("PI_B", g2(proof.pi_b))}
${rustArr("PI_C", g1(proof.pi_c))}

${rustArr2("PUB_SIGNALS", pubRows)}
`;

const dest = resolve(here, "../../contracts/zentra-verifier/src/spike_fixtures.rs");
writeFileSync(dest, out);
console.log(`wrote ${dest}`);
console.log(`  IC points: ${icRows.length}, public signals: ${pubRows.length} (${pub.join(",")})`);
